-- SQLite
SELECT EVENT_UNIQUE_ID, PRIMARY_OFFENCE, OCC_DATE, OCC_YEAR, OCC_MONTH, OCC_DOW, OCC_DAY, OCC_DOY, OCC_HOUR, REPORT_DATE, REPORT_YEAR, REPORT_MONTH, REPORT_DOW, REPORT_DAY, REPORT_DOY, REPORT_HOUR, DIVISION, LOCATION_TYPE, PREMISES_TYPE, BIKE_MAKE, BIKE_MODEL, BIKE_TYPE, BIKE_SPEED, BIKE_COLOUR, BIKE_COST, STATUS, NEIGHBOURHOOD_158, NEIGHBOURHOOD_140, LONG_WGS84, LAT_WGS84
FROM info;
-- Choose the columns only we need for mapping 
select NEIGHBOURHOOD_158,LONG_WGS84,LAT_WGS84
FROM info WHERE STATUS = 'STOLEN' order by NEIGHBOURHOOD_158;

SELECT NEIGHBOURHOOD_158,LONG_WGS84,LAT_WGS84
FROM info
WHERE STATUS = 'STOLEN'
GROUP BY NEIGHBOURHOOD_158;

-- Neighbourhood and its lat lng
SELECT min(NEIGHBOURHOOD_158), LONG_WGS84, LAT_WGS84
FROM info
WHERE STATUS = 'STOLEN'
GROUP BY NEIGHBOURHOOD_158

-- Neighbourhood and counts
SELECT info.NEIGHBOURHOOD_158, count(info.NEIGHBOURHOOD_158), latlnginfo.LONG_WGS84, latlnginfo.LAT_WGS84
FROM info
INNER JOIN (
    SELECT min(NEIGHBOURHOOD_158) as NEIGHBOURHOOD, LONG_WGS84, LAT_WGS84
    FROM info
    WHERE STATUS = 'STOLEN'
    GROUP BY NEIGHBOURHOOD_158
) latlnginfo ON info.NEIGHBOURHOOD_158= latlnginfo.NEIGHBOURHOOD
WHERE STATUS = 'STOLEN'
GROUP BY NEIGHBOURHOOD_158;